#!/usr/bin/env node
'use strict';
// ── THE SWEEP ───────────────────────────────────────────────────────────────
//
//   node scripts/schema-sweep.js              what is at risk, and where
//   node scripts/schema-sweep.js --alters      the ALTER statements themselves
//   node scripts/schema-sweep.js --write       regenerate server/schema-manifest.json
//   node scripts/schema-sweep.js --check       exit 1 if the manifest is stale
//   node scripts/schema-sweep.js --live        what THIS database is actually missing
//
// CREATE TABLE IF NOT EXISTS is a no-op on a table that already exists. So a
// column added to a CREATE block reaches every fresh database and never reaches
// production, and surfaces days later as `column "x" does not exist` from a
// query nobody touched. deal_comps.brand and deal_comps.school were the same
// mistake on the same table in the same week; email_verify_credit_log and
// market_deepen_log were the two before that.
//
// 907 columns across 96 tables are declared only inside a CREATE. Writing 907
// ALTER statements by hand fixes today and nothing else -- the 908th column
// lands tomorrow with the same defect, and 907 no-op ALTERs on every boot each
// take a lock for nothing.
//
// So the sweep produces a MANIFEST -- the full expected shape, committed -- and
// services/schemaReconcile diffs it against information_schema at startup in one
// query and adds only what is genuinely absent. A new column in a CREATE block
// is picked up automatically, and tests/schemasweep.js fails if the committed
// manifest and the source ever disagree.

const fs = require('fs');
const path = require('path');
const S = require('./lib/schemaScan');

const REPO = path.join(__dirname, '..');
const MANIFEST = path.join(REPO, 'server', 'schema-manifest.json');
const ROOTS = [path.join(REPO, 'server'), path.join(REPO, 'scripts')];

const args = process.argv.slice(2);
const has = (f) => args.includes(f);

function build() {
  const r = S.scan(ROOTS);
  const tables = {};
  for (const [table, rec] of r.creates) {
    if (table.startsWith('_')) continue;
    const cols = {};
    for (const [name, col] of [...rec.columns].sort((a, b) => a[0].localeCompare(b[0]))) {
      cols[name] = S.alterFor(table, col).replace(
        new RegExp('^ALTER TABLE ' + table + ' ADD COLUMN IF NOT EXISTS ' + name + ' '), '');
    }
    tables[table] = cols;
  }
  const ordered = {};
  for (const k of Object.keys(tables).sort()) ordered[k] = tables[k];
  return { scan: r, manifest: {
    note: 'GENERATED by scripts/schema-sweep.js --write. Do not hand-edit. '
      + 'Every column declared in a CREATE TABLE IF NOT EXISTS, with the definition an '
      + 'ALTER may carry (NOT NULL / PRIMARY KEY / UNIQUE stripped, since neither can be '
      + 'added to a table that already holds rows). services/schemaReconcile diffs this '
      + 'against information_schema at startup.',
    tables: ordered,
  } };
}

async function live(manifest) {
  const store = require('../server/store');
  const P = store.pool;
  await new Promise((r) => setTimeout(r, 4000));   // let init settle
  const names = Object.keys(manifest.tables);
  const r = await P.query(
    `SELECT table_name, column_name FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = ANY($1)`, [names]);
  const got = new Map();
  for (const row of r.rows) {
    if (!got.has(row.table_name)) got.set(row.table_name, new Set());
    got.get(row.table_name).add(row.column_name);
  }
  let missing = 0, absent = 0;
  for (const t of names) {
    const have = got.get(t);
    if (!have) { absent++; continue; }              // table not created here at all
    const gaps = Object.keys(manifest.tables[t]).filter((c) => !have.has(c));
    if (!gaps.length) continue;
    missing += gaps.length;
    console.log(`\n  ${t}`);
    for (const c of gaps) console.log(`    MISSING ${c}  ${manifest.tables[t][c]}`);
  }
  console.log(`\n${missing} column(s) missing from this database across `
    + `${names.length - absent} existing table(s); ${absent} table(s) not present here.`);
  await P.end();
}

async function main() {
  const { scan, manifest } = build();

  if (has('--write')) {
    fs.writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2) + '\n');
    const n = Object.values(manifest.tables).reduce((a, c) => a + Object.keys(c).length, 0);
    console.log(`Wrote ${path.relative(REPO, MANIFEST)}: `
      + `${Object.keys(manifest.tables).length} tables, ${n} columns.`);
    return;
  }

  if (has('--check')) {
    const on = fs.existsSync(MANIFEST) ? fs.readFileSync(MANIFEST, 'utf8') : '';
    const want = JSON.stringify(manifest, null, 2) + '\n';
    if (on === want) { console.log('Manifest is current.'); return; }
    console.error('MANIFEST IS STALE. Run: node scripts/schema-sweep.js --write');
    process.exit(1);
  }

  if (has('--live')) { await live(manifest); return; }

  if (has('--alters')) {
    for (const g of scan.gaps) console.log(g.alter + ';');
    return;
  }

  // ── THE REPORT ────────────────────────────────────────────────────────────
  const byTable = new Map();
  for (const g of scan.gaps) {
    if (!byTable.has(g.table)) byTable.set(g.table, []);
    byTable.get(g.table).push(g);
  }
  const cols = [...scan.creates.values()].reduce((a, r) => a + r.columns.size, 0);
  console.log(`\nScanned ${scan.files.length} file(s): `
    + `${scan.creates.size} tables, ${cols} columns declared in CREATE blocks.`);
  if (scan.skipped.length) {
    console.log(`\n${scan.skipped.length} CREATE statement(s) COULD NOT BE PARSED `
      + '— these tables are NOT covered by the sweep:');
    for (const s of scan.skipped) console.log(`  ${s.table}  ${s.file}:${s.line}`);
  }
  console.log(`\n${scan.gaps.length} column(s) exist ONLY inside a CREATE TABLE IF NOT EXISTS `
    + `across ${byTable.size} table(s).`);
  console.log('On a database where the table predates the column, every one of these is a '
    + '`column does not exist` waiting to happen.\n');
  for (const [t, gs] of [...byTable].sort((a, b) => b[1].length - a[1].length)) {
    console.log(`  ${String(gs.length).padStart(3)}  ${t}`);
  }
  console.log('\nThese are covered by server/schema-manifest.json + services/schemaReconcile,');
  console.log('which adds the missing ones at startup. --live shows what one database lacks.');
}

main().catch((e) => { console.error(e); process.exit(1); });
