-- server/migrations/006_nil_director_dashboard.sql
-- NIL Director Dashboard — University-Side Tooling
--
-- SAFETY: All IF NOT EXISTS. Zero impact on existing tables.
--         Does NOT touch: athletes, deals, users, universities,
--         outreach_logs, brand_contacts, brand_match_scores,
--         nil_activity_log, ingestion_events, roster_discovery_jobs,
--         roster_review_queue, automation_scheduler_log.
--
-- WHAT THIS ADDS:
--   1. university_deal_pipeline  — university-managed NIL deal CRM
--   2. athlete_contact_log       — staff notes, emails, calls, meetings
--   3. university_daily_actions  — pre-computed action queue for directors
--   4. VIEW university_program_summary — per-university athlete + deal totals
--
-- Run via: node server/migrations/run.js
-- Or paste directly into Railway PostgreSQL query console.

-- ── 1. University Deal Pipeline ───────────────────────────────────────────────
-- University-managed NIL deal tracking, separate from the agent deal CRM.
-- Allows compliance officers and NIL directors to track every active deal,
-- its disclosure status, and important dates independently of agent workflows.
CREATE TABLE IF NOT EXISTS university_deal_pipeline (
  id                 TEXT         PRIMARY KEY,
  university_id      TEXT         NOT NULL,
  athlete_id         TEXT         NOT NULL,
  brand              TEXT         NOT NULL,
  deal_value         INTEGER      NOT NULL DEFAULT 0,

  deal_type          TEXT
                       CHECK (deal_type IN (
                         'social', 'appearance', 'licensing', 'ambassador', 'other'
                       )),

  status             TEXT         NOT NULL DEFAULT 'pending'
                       CHECK (status IN (
                         'pending', 'active', 'completed', 'expiring', 'rejected'
                       )),

  start_date         DATE,
  end_date           DATE,

  -- Tracks whether the deal has been properly disclosed to the institution.
  disclosure_status  TEXT         NOT NULL DEFAULT 'pending'
                       CHECK (disclosure_status IN (
                         'pending', 'submitted', 'approved', 'missing'
                       )),

  notes              TEXT,
  created_by         TEXT,        -- user_id of the staff member who created the record
  created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS udp_university_idx  ON university_deal_pipeline (university_id);
CREATE INDEX IF NOT EXISTS udp_athlete_idx     ON university_deal_pipeline (athlete_id);
CREATE INDEX IF NOT EXISTS udp_status_idx      ON university_deal_pipeline (status);
CREATE INDEX IF NOT EXISTS udp_end_date_idx    ON university_deal_pipeline (end_date);

-- ── 2. Athlete Contact Log ────────────────────────────────────────────────────
-- Staff-facing communication and note history attached to each athlete record.
-- Supports multiple contact_types so directors can log calls, emails, meetings,
-- and automated system alerts all in one feed.
CREATE TABLE IF NOT EXISTS athlete_contact_log (
  id             BIGSERIAL    PRIMARY KEY,
  university_id  TEXT         NOT NULL,
  athlete_id     TEXT         NOT NULL,
  staff_user_id  TEXT,        -- NULL if the entry was generated by an automated system

  contact_type   TEXT         NOT NULL DEFAULT 'note'
                   CHECK (contact_type IN (
                     'note', 'email', 'call', 'meeting', 'alert', 'system'
                   )),

  subject        TEXT,
  body           TEXT         NOT NULL,

  -- Pinned notes float to the top of the athlete's contact feed.
  is_pinned      BOOLEAN      NOT NULL DEFAULT false,

  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Composite index for the primary fetch pattern: all entries for one athlete
-- at a university, most-recent first.
CREATE INDEX IF NOT EXISTS acl_athlete_univ_idx  ON athlete_contact_log (university_id, athlete_id);
CREATE INDEX IF NOT EXISTS acl_created_at_idx    ON athlete_contact_log (created_at DESC);
CREATE INDEX IF NOT EXISTS acl_contact_type_idx  ON athlete_contact_log (contact_type);

-- ── 3. University Daily Actions ───────────────────────────────────────────────
-- Pre-computed action queue surfaced on the NIL director's dashboard.
-- Rows are generated by a scheduled job or on-demand recalculation;
-- directors can dismiss items without deleting them (audit trail preserved).
CREATE TABLE IF NOT EXISTS university_daily_actions (
  id              BIGSERIAL    PRIMARY KEY,
  university_id   TEXT         NOT NULL,

  action_type     TEXT         NOT NULL
                    CHECK (action_type IN (
                      'follow_up', 'deal_review', 'compliance',
                      'renewal', 'outreach', 'approval'
                    )),

  -- 1 = lowest urgency, 10 = highest urgency.
  priority        INTEGER      NOT NULL DEFAULT 5
                    CHECK (priority BETWEEN 1 AND 10),

  title           TEXT         NOT NULL,
  detail          TEXT,

  -- Optional links to related records.
  athlete_id      TEXT,
  deal_id         TEXT,

  due_date        DATE,

  -- Soft-delete: dismissed actions are hidden from the live queue
  -- but retained for reporting.
  is_dismissed    BOOLEAN      NOT NULL DEFAULT false,
  dismissed_by    TEXT,        -- user_id
  dismissed_at    TIMESTAMPTZ,

  -- true = created by automated job; false = manually entered by staff.
  auto_generated  BOOLEAN      NOT NULL DEFAULT true,

  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  -- Stale actions beyond this timestamp are excluded from the live queue
  -- even if not explicitly dismissed.
  expires_at      TIMESTAMPTZ
);

-- Primary queue fetch: undismissed actions for a university ordered by due date.
CREATE INDEX IF NOT EXISTS uda_queue_idx       ON university_daily_actions (university_id, is_dismissed, due_date);
CREATE INDEX IF NOT EXISTS uda_athlete_idx     ON university_daily_actions (athlete_id);
CREATE INDEX IF NOT EXISTS uda_action_type_idx ON university_daily_actions (action_type);

-- ── 4. VIEW: university_program_summary ──────────────────────────────────────
-- Aggregated snapshot of each university's NIL program health.
-- Uses LEFT JOIN + COALESCE so universities with zero athletes or zero deals
-- still appear with counts of 0 rather than being dropped from the result set.
CREATE OR REPLACE VIEW university_program_summary AS
SELECT
  u.id                                            AS university_id,
  u.name                                          AS university_name,
  u.conference,
  u.state,

  -- Total athletes associated with this university.
  COALESCE(a.athlete_count, 0)                    AS athlete_count,

  -- Deal pipeline totals.
  COALESCE(dp.total_deals, 0)                     AS total_deals,
  COALESCE(dp.active_deals, 0)                    AS active_deals,
  COALESCE(dp.pending_deals, 0)                   AS pending_deals,
  COALESCE(dp.expiring_deals, 0)                  AS expiring_deals,

  -- Total contracted value across all non-rejected deals.
  COALESCE(dp.total_deal_value, 0)                AS total_deal_value,

  -- Disclosure health: how many deals still need attention.
  COALESCE(dp.disclosure_pending, 0)              AS disclosure_pending,
  COALESCE(dp.disclosure_missing, 0)              AS disclosure_missing

FROM universities u

-- Athlete count subquery.
LEFT JOIN (
  SELECT
    university_id,
    COUNT(*)   AS athlete_count
  FROM athletes
  GROUP BY university_id
) a ON a.university_id = u.id

-- Deal pipeline summary subquery.
LEFT JOIN (
  SELECT
    university_id,
    COUNT(*)                                              AS total_deals,
    COUNT(*) FILTER (WHERE status = 'active')             AS active_deals,
    COUNT(*) FILTER (WHERE status = 'pending')            AS pending_deals,
    COUNT(*) FILTER (WHERE status = 'expiring')           AS expiring_deals,
    COALESCE(SUM(deal_value) FILTER (
      WHERE status NOT IN ('rejected')
    ), 0)                                                 AS total_deal_value,
    COUNT(*) FILTER (WHERE disclosure_status = 'pending') AS disclosure_pending,
    COUNT(*) FILTER (WHERE disclosure_status = 'missing') AS disclosure_missing
  FROM university_deal_pipeline
  GROUP BY university_id
) dp ON dp.university_id = u.id;
